#!/bin/bash
# This script uses multi-gitter to update DeepModeling email addresses
# across all repositories in the deepmodeling organization.

multi-gitter run "uv run $PWD/update-email.py" \
  --author-email "48687836+njzjz-bot@users.noreply.github.com" \
  --author-name "njzjz-bot[bot]" \
  -B update-deepmodeling-email \
  --fork \
  -m 'docs: update DeepModeling email address

Update the DeepModeling email from contact@deepmodeling.org to deepmodeling@deepmodeling.com.
The former is no longer used.

Generated by the task: https://github.com/njzjz-bot/njzjz-bot/issues/14.
' \
  --git-type cmd \
  -O deepmodeling \
  --conflict-strategy replace \
  "$@"
