#!/bin/bash
# This script uses multi-gitter to update DeepModeling email addresses
# across all repositories in the deepmodeling organization.

multi-gitter run "uv run $PWD/update-email.py" \
  --author-email "48687836+njzjz-bot@users.noreply.github.com" \
  --author-name "njzjz-bot[bot]" \
  -B update-deepmodeling-email \
  --fork \
  -m 'docs: update DeepModeling email address

Update the DeepModeling email from contact@deepmodeling.org to deepmodeling@deepmodeling.com.
The former is no longer used.

Generated by the task: https://github.com/njzjz-bot/njzjz-bot/issues/14.
' \
  --git-type cmd \
  -R deepmodeling/deepmd-kit \
  -R deepmodeling/Uni-Mol \
  -R deepmodeling/jax-fem \
  -R deepmodeling/dpgen \
  -R deepmodeling/dpdata \
  -R deepmodeling/DMFF \
  -R deepmodeling/CrystalFormer \
  -R deepmodeling/deepks-kit \
  -R deepmodeling/AI4Science101 \
  -R deepmodeling/reacnetgenerator \
  -R deepmodeling/DeePTB \
  -R deepmodeling/community \
  -R deepmodeling/SciAssess \
  -R deepmodeling/sciencepedia \
  -R deepmodeling/AI4S-agent-tools \
  -R deepmodeling/dpdispatcher \
  -R deepmodeling/deepmd-gnn \
  -R deepmodeling/rid-kit \
  -R deepmodeling/APEX \
  -R deepmodeling/build-your-agent \
  -R deepmodeling/dpti \
  -R deepmodeling/unimol_tools \
  -R deepmodeling/openlam \
  -R deepmodeling/ABACUS-agent-tools \
  -R deepmodeling/AIS-Square \
  -R deepmodeling/tutorials \
  -R deepmodeling/tbplas \
  -R deepmodeling/dftio \
  -R deepmodeling/LAMBench \
  -R deepmodeling/dpgui \
  -R deepmodeling/deepmodeling-projects \
  -R deepmodeling/dargs \
  -R deepmodeling/DeePDih \
  -R deepmodeling/tutorials-cn \
  -R deepmodeling/GROMACS \
  -R deepmodeling/workflows \
  -R deepmodeling/blog \
  -R deepmodeling/deepmodeling_sphinx \
  -R deepmodeling/docs \
  -R deepmodeling/fpop \
  -R deepmodeling/args \
  -R deepmodeling/deepmodeling.github.io \
  -R deepmodeling/dflow-op-cutter \
  -R deepmodeling/openfinite \
  -R deepmodeling/Uni-Electrolyte \
  -R deepmodeling/cemo \
  -R deepmodeling/.github \
  --conflict-strategy replace \
  "$@"
