#!/bin/bash
# This script uses multi-gitter to fix the DeepModeling brand name
# from "Deep Modeling" (with space) to "DeepModeling" (no space)
# across all repositories in the deepmodeling organization.

multi-gitter run "uv run $PWD/fix-name.py" \
  --author-email "48687836+njzjz-bot@users.noreply.github.com" \
  --author-name "njzjz-bot[bot]" \
  -B fix-deepmodeling-name \
  --fork \
  -m 'docs: fix DeepModeling brand name

Change "Deep Modeling" (with space) to "DeepModeling" (no space).
"Deep Modeling" is an incorrect brand name. The correct one is "DeepModeling".

Generated by the task: https://github.com/njzjz-bot/njzjz-bot/issues/19.
' \
  --git-type cmd \
  -O deepmodeling \
  --repo-exclude deepmodeling/sciencepedia \
  --conflict-strategy replace \
  "$@"
