#!/bin/bash
# This script uses multi-gitter to update ruff settings
# from tool.ruff to tool.ruff.lint across multiple repositories.

multi-gitter run "uv run $PWD/update-ruff-settings.py" \
  --author-email "48687836+njzjz-bot@users.noreply.github.com" \
  --author-name "njzjz-bot[bot]" \
  -B update-ruff-settings \
  --fork \
  -m 'build: update ruff settings to use tool.ruff.lint

Move deprecated top-level ruff settings to the lint section.
The top-level linter settings are deprecated in favor of their
counterparts in the lint section.

This updates settings like:
- ignore -> lint.ignore
- ignore-init-module-imports -> lint.ignore-init-module-imports
- select -> lint.select
- pydocstyle -> lint.pydocstyle

Generated by the task: https://github.com/njzjz-bot/njzjz-bot/issues/5.
' \
  --git-type cmd \
  -O deepmodeling \
  -O njzjz \
  --repo-exclude deepmodeling/sciencepedia \
  --conflict-strategy replace \
  "$@"
