#!/bin/bash
# This script uses multi-gitter to run the sphinx-book-theme replacement task
# across multiple repositories.

multi-gitter run "python $PWD/sphinx-book-theme.py" \
  --author-email "48687836+njzjz-bot@users.noreply.github.com" \
  --author-name "njzjz-bot[bot]" \
  -B sphinx-book-theme \
  --fork \
  -m 'docs: replace sphinx-rtd-theme with sphinx-book-theme

Compared to `sphinx-rtd-theme`, `sphinx-book-theme` is a clean and modern Sphinx theme.

Generated by the task: https://github.com/njzjz-bot/njzjz-bot/issues/11.
' \
  --git-type cmd \
  -R deepmodeling/dargs \
  --conflict-strategy replace \
  "$@"
