#!/bin/bash
# This script uses multi-gitter to update DeepModeling domain
# across all repositories in the deepmodeling organization.

multi-gitter run "uv run $PWD/update-domain.py" \
  --author-email "48687836+njzjz-bot@users.noreply.github.com" \
  --author-name "njzjz-bot[bot]" \
  -B update-deepmodeling-domain \
  --fork \
  -m 'docs: update DeepModeling domain to deepmodeling.com

Update the DeepModeling domain from deepmodeling.org to deepmodeling.com.
The former is no longer used.

Generated by the task: https://github.com/njzjz-bot/njzjz-bot/issues/23.
' \
  --git-type cmd \
  -O deepmodeling \
  --repo-exclude deepmodeling/sciencepedia \
  --conflict-strategy replace \
  "$@"
